### ISSUE TITLE
opener "tail" is over dropdown content

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-dropdown-ui#10]
The mechanism used to show the dropdown balloon "tail" is being positioned overtop of the content inside the dropdown. This only really manifests itself when the content doesn't have padding. Screenshot:

![screen shot](https://cloud.githubusercontent.com/assets/5491151/15340906/dcf618a2-1c59-11e6-9158-cb36755f8886.png)

**Comment by dbatiste** [comment]
So I spoke to Dana about this issue - he isn't concerned about this since he said there will always be padding.  I think he wants to reduce the size of the arrow slightly, so that will reduce the chances of this coming up a bit.  Nevertheless, I still think it would be good to swap for an SVG though to address this altogether.

**Comment by geurts** [comment]
Could it be solved by raising the z-index of the list items above the diamond thingy?

**Comment by dbatiste** [comment]
Possibly, but not the element that has the border since we're purposely trying to position the tail overtop of the top border.
