### ISSUE TITLE
handle very large dropdown heights somehow

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-dropdown-ui#18]
See attached. When the dropdown contents are very tall, the user may need to scroll the outer page in order to see everything. In MVC, "flyouts" cannot be any taller than the viewport, and when they are we make their contents scrollable.

![screen shot 2016-05-25 at 12 12 25 pm](https://cloud.githubusercontent.com/assets/5491151/15547477/fa545134-2271-11e6-824b-22fcfe519065.png)

**Comment by geurts** [comment]
If we opted for the user to scroll the PAGE instead of the contents of the dropdown, then we may have a problem when LMS pages have little to no content on them, right? The menu would overflow off-screen and the user wouldn't be able to scroll to see the rest of it?

I like what we do in the LMS today, where the contents become scrollable.

**Comment by dbatiste** [comment]
Auto-fit capability has been added for generic dropdown.  For dropdown-menu, auto-fit is disabled due to design constraint (we can re-open if needed with possible changes to menu design).
